version: '3'

services:
  web:
    build: .
    container_name: web
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks:
      hillel:
        ipv4_address: 10.0.0.2
  mysql:
     image: mysql
     container_name: db
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: password123
     volumes:
       - ./script.sql:/docker-entrypoint-initdb.d/script.sql
       - ./db:/var/lib/mysql
     networks:
       hillel:
         ipv4_address: 10.0.0.3
networks:
  hillel:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/24
